In [1]:
import pandas as pd
import numpy as np
from glob import glob

weather_flower = {"Anthurium":["C0V360_內門", "C0X060_下營"],
                  "Chrysanthemum":["C0K490_古坑"],
                  "Eustoma":["467480_嘉義", "C0G650_員林"],
                  "OrientalLily":["C0F9L0_后里"],
                  "Rose":["C0H960_草屯", "C0R590_里港"]}

In [2]:
# weather_flower["Anthurium"]

In [3]:
# 日期 均溫 最高溫 最低溫 降水量 相對溼度 測站氣壓 風速 最大陣風
# 平均價格 總銷售量 年份 週別 花種類

In [4]:
def weather_join_flower(w_s, flower):
    print(w_s, flower)
    fn_w = glob("../result/merge_weather/"+ w_s +"*.csv")[0]
    fn_f = glob("../result/merge_flower_allmarket_price/merge_"+ flower + "*.csv")[0]
    df_w = pd.read_csv(fn_w, encoding="utf-8")
    df_f = pd.read_csv(fn_f, encoding="utf-8")
    df_j = df_w.join(df_f.set_index("date"), on="Date")
    fn_save = "../result/join_weather_flower/" + flower + "_" + w_s + ".csv"
    df_j.to_csv(fn_save, index=False, encoding="utf-8")
    print("saved")

In [5]:
flowers = list(weather_flower.keys())
for flower in flowers:
    w_s = weather_flower[flower][0]
    weather_join_flower(w_s, flower)

C0V360_內門 Anthurium
saved
C0K490_古坑 Chrysanthemum
saved
467480_嘉義 Eustoma
saved
C0F9L0_后里 OrientalLily
saved
C0H960_草屯 Rose
saved

In [11]:
df = pd.read_csv("../result/join_weather_flower/Rose_C0H960_草屯.csv")
df_s = df.sort_values(["year", "week"])
df_s

,Date,Temperature,T.Max,T.Min,Precp,RH,StnPres,WS,WSGust,avg_price,total_count,year,week,flower
0,2014-01-01,17.5,25.0,11.4,0.0,70,1003.0,0.7,3.8,187.723,3813.0,2014.0,1.0,Rose
1,2014-01-02,19.8,27.1,13.5,0.0,65,1001.5,0.9,3.5,188.338,4506.0,2014.0,1.0,Rose
2,2014-01-03,20.7,26.3,16.7,1.5,73,999.7,0.8,4.5,173.910,5283.0,2014.0,1.0,Rose
3,2014-01-04,18.1,22.4,13.9,0.0,69,1000.4,0.5,3.9,162.160,2398.0,2014.0,1.0,Rose
4,2014-01-05,16.1,23.4,11.1,0.0,66,1002.3,0.7,3.6,173.248,2842.0,2014.0,1.0,Rose
5,2014-01-06,16.2,22.5,12.2,0.0,71,1002.8,0.6,4.3,149.852,6076.0,2014.0,1.0,Rose
6,2014-01-07,18.2,25.4,12.7,0.0,72,1002.1,0.8,4.3,167.129,4134.0,2014.0,1.0,Rose
7,2014-01-08,18.9,25.3,14.9,0.0,70,1002.4,1.2,6.4,183.379,3531.0,2014.0,2.0,Rose
8,2014-01-09,15.1,19.4,13.4,0.0,70,1005.9,0.9,8.0,180.495,4488.0,2014.0,2.0,Rose
9,2014-01-10,16.1,22.3,13.1,0.0,72,1007.9,0.8,5.2,165.647,6400.0,2014.0,2.0,Rose
10,2014-01-11,16.9,23.9,11.7,0.0,80,1007.9,0.9,5.5,148.534,3672.0,2014.0,2.0,Rose
11,2014-01-12,17.5,23.6,14.0,0.0,78,1007.2,1.2,7.1,153.654,2540.0,2014.0,2.0,Rose
12,2014-01-13,16.2,21.0,13.8,0.0,74,1005.0,1.0,6.1,153.655,5726.0,2014.0,2.0,Rose
13,2014-01-14,14.4,18.1,11.7,0.0,78,1004.6,1.1,7.5,152.343,4502.0,2014.0,2.0,Rose
14,2014-01-15,14.7,21.5,10.5,0.0,64,1006.3,0.8,5.8,153.610,4571.0,2014.0,3.0,Rose
15,2014-01-16,15.9,22.8,10.1,0.0,65,1006.9,0.8,4.8,151.489,5200.0,2014.0,3.0,Rose
16,2014-01-17,16.6,24.5,11.3,0.0,67,1005.9,0.7,6.4,146.700,6028.0,2014.0,3.0,Rose
17,2014-01-18,14.2,20.4,10.1,0.0,62,1008.9,1.0,10.5,146.578,2853.0,2014.0,3.0,Rose
18,2014-01-19,14.3,20.8,7.6,0.0,64,1009.0,1.5,7.3,148.860,2012.0,2014.0,3.0,Rose
19,2014-01-20,15.2,22.3,10.7,0.0,73,1007.6,0.8,5.2,140.910,5119.0,2014.0,3.0,Rose
20,2014-01-21,12.8,17.7,8.6,0.0,65,1006.2,1.1,7.5,147.730,4273.0,2014.0,3.0,Rose
21,2014-01-22,11.9,18.5,6.8,0.0,60,1007.2,0.9,5.9,164.032,3012.0,2014.0,4.0,Rose
22,2014-01-23,13.2,21.3,6.7,0.0,61,1006.7,1.0,5.4,175.320,3129.0,2014.0,4.0,Rose
23,2014-01-24,14.8,22.0,8.2,0.0,53,1004.5,1.0,5.9,168.110,3194.0,2014.0,4.0,Rose
24,2014-01-25,16.7,25.2,8.9,0.0,53,1003.3,1.2,8.1,159.760,3281.0,2014.0,4.0,Rose
25,2014-01-26,15.9,22.3,11.1,0.0,66,1003.6,0.8,5.3,179.272,2394.0,2014.0,4.0,Rose
26,2014-01-27,16.7,23.0,13.1,0.0,69,1004.2,0.8,4.8,195.056,4134.0,2014.0,4.0,Rose
27,2014-01-28,17.4,25.8,11.6,0.0,72,1004.3,0.8,4.3,214.075,5728.0,2014.0,4.0,Rose
28,2014-01-29,18.0,24.8,12.0,0.0,70,1003.9,0.9,5.0,150.132,7141.0,2014.0,5.0,Rose
29,2014-01-30,18.8,26.3,12.4,0.0,59,1003.9,0.7,4.4,96.460,2136.0,2014.0,5.0,Rose
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1856,2019-02-18,20.9,27.8,16.3,0.0,77,1000.9,0.8,4.6,NaN,NaN,NaN,NaN,NaN
1857,2019-02-19,22.8,28.5,16.5,0.0,79,1003.2,1.4,6.9,NaN,NaN,NaN,NaN,NaN
1858,2019-02-20,23.6,29.8,19.6,0.0,81,1004.8,1.0,7.8,NaN,NaN,NaN,NaN,NaN
1859,2019-02-21,22.3,27.6,18.6,0.0,84,1003.1,0.9,6.7,NaN,NaN,NaN,NaN,NaN
1860,2019-02-22,20.6,26.7,17.5,0.0,80,1001.8,0.8,6.5,NaN,NaN,NaN,NaN,NaN
1861,2019-02-23,17.7,21.4,15.7,0.0,72,1001.2,0.8,4.6,NaN,NaN,NaN,NaN,NaN
1862,2019-02-24,16.3,18.6,14.9,7.0,94,1000.6,1.0,5.3,NaN,NaN,NaN,NaN,NaN
1863,2019-02-25,19.7,27.2,15.5,0.0,80,1001.2,0.6,5.9,NaN,NaN,NaN,NaN,NaN
1864,2019-02-26,20.6,28.3,16.3,0.0,77,1002.0,0.9,4.8,NaN,NaN,NaN,NaN,NaN
1865,2019-02-27,21.7,27.2,18.1,0.0,74,1000.8,0.7,5.9,NaN,NaN,NaN,NaN,NaN
1866,2019-02-28,22.7,27.7,19.1,0.0,73,1000.1,0.8,6.5,NaN,NaN,NaN,NaN,NaN
1867,2019-03-01,21.4,28.4,17.3,0.0,77,1001.2,0.6,4.6,NaN,NaN,NaN,NaN,NaN
1868,2019-03-02,22.3,27.3,18.8,0.0,80,998.2,1.1,5.0,NaN,NaN,NaN,NaN,NaN
1869,2019-03-03,20.1,26.1,16.9,6.0,86,996.3,1.7,9.4,NaN,NaN,NaN,NaN,NaN
1870,2019-03-04,21.0,27.0,16.3,0.0,76,999.3,0.6,5.4,NaN,NaN,NaN,NaN,NaN
1871,2019-03-05,20.6,26.6,16.2,4.5,80,998.5,1.7,6.8,NaN,NaN,NaN,NaN,NaN
1872,2019-03-06,20.2,28.1,16.5,5.0,87,999.3,1.0,10.6,NaN,NaN,NaN,NaN,NaN
1873,2019-03-07,14.6,18.4,12.2,38.5,100,1001.1,0.5,5.0,NaN,NaN,NaN,NaN,NaN
1874,2019-03-08,15.3,20.2,11.9,15.0,97,1001.1,0.9,7.2,NaN,NaN,NaN,NaN,NaN
1875,2019-03-09,18.1,20.8,15.7,27.5,100,997.2,1.2,5.4,NaN,NaN,NaN,NaN,NaN
1876,2019-03-10,19.1,23.0,16.7,25.5,91,997.8,1.5,10.6,NaN,NaN,NaN,NaN,NaN
1877,2019-03-11,18.1,20.0,16.6,0.0,90,998.6,0.5,3.8,NaN,NaN,NaN,NaN,NaN
1878,2019-03-12,21.0,26.9,16.6,0.0,69,1000.4,1.1,6.6,NaN,NaN,NaN,NaN,NaN
1879,2019-03-13,22.0,26.6,18.8,0.0,68,1003.2,0.9,4.3,NaN,NaN,NaN,NaN,NaN
1880,2019-03-14,21.4,27.3,17.4,0.0,73,1003.7,1.0,5.8,NaN,NaN,NaN,NaN,NaN
1881,2019-03-15,18.6,21.1,16.2,0.0,71,1004.3,0.8,6.8,NaN,NaN,NaN,NaN,NaN
1882,2019-03-16,20.8,24.1,17.1,0.0,70,1003.4,1.3,6.5,NaN,NaN,NaN,NaN,NaN
1883,2019-03-17,21.3,25.4,18.9,0.0,75,1003.7,1.0,4.6,NaN,NaN,NaN,NaN,NaN
1884,2019-03-18,22.0,28.9,18.4,0.0,81,1001.6,0.8,6.0,NaN,NaN,NaN,NaN,NaN
1885,2019-03-19,23.8,30.5,18.9,0.0,75,1000.0,1.0,4.6,NaN,NaN,NaN,NaN,NaN

In [7]:
# df_s = df_j.sort_values(["year", "week"])
# df_s.to_csv("sorted0503.csv")