In [1]:
import pandas as pd 
import numpy as np
from collections import Counter
df = pd.read_csv("finaldata_0404.csv", encoding="utf-8", sep=",")

In [2]:
df

,統一編號,營業人名稱,資本額,使用統一發票,設立日期,停業日期,組織別名稱,營業地址,殯葬,餐廳,花卉相關銷售,花卉栽種,目前狀態
0,94920851,保証責任南投縣和興合作農場,200000,N,2003-05-26,2018-07-12,0,南投縣中寮鄉和興村００８鄰永樂路１４３號,0,0,1,0,die
1,45651105,祥林園藝,90000,N,2008-04-11,2019-01-01,0,南投縣仁愛鄉南豐村１２鄰中正路１１８－３號,0,0,1,0,die
2,80590886,松濤園企業有限公司,1200000,N,2003-11-19,2018-06-01,0,南投縣南投市光輝里省府路７８號,0,0,1,1,die
3,14606346,百合園藝,50000,N,2002-09-16,2017-09-30,0,南投縣南投市南投里２鄰民權街８７號,0,0,1,0,die
4,39919339,中興蘭園,200000,N,2013-12-10,2017-09-11,0,南投縣南投市營北里仁義南路３４巷７號,0,0,1,0,die
5,19258866,松柏林園藝綠化土木工程行,3000,N,2000-11-06,2018-08-21,0,南投縣國姓鄉北港村北原路６８－２號,0,0,0,1,die
6,78121043,文通林業行,600000,Y,1997-06-20,2019-02-28,0,南投縣埔里鎮北安里三民路２６巷１０號１樓,0,0,1,1,die
7,10920667,尚宏山業行,6000000,N,2010-12-23,2019-01-30,0,南投縣埔里鎮北安里１７鄰和平東路５３６號１樓,0,0,1,0,die
8,80088169,順瓏農產有限公司,5000000,Y,2003-01-28,2019-02-01,0,南投縣埔里鎮北梅里１８鄰仁愛路５１１號,0,0,1,0,die
9,62164967,統裕行,4700000,N,1971-04-01,2018-06-30,0,南投縣埔里鎮同聲里光華街９５巷３號１樓,0,0,1,1,die
10,42742309,美宥美企業有限公司,1000000,N,2015-11-02,2018-08-21,0,南投縣埔里鎮泰安里民族街７８號１樓,0,0,1,0,die
11,53975780,宿山企業有限公司,500000,N,2012-08-22,2018-10-01,0,南投縣埔里鎮麒麟里過坑路７８號１樓,0,0,1,0,die
12,28316254,一家國際生活館有限公司,1000000,N,2006-05-17,2018-09-01,0,南投縣水里鄉北埔村１２鄰民族路１７１號１、２樓,0,0,1,0,die
13,9345048,太朴松濤園,200000,N,2006-04-24,2019-03-03,0,南投縣水里鄉永興村林朋巷１７８－３號,0,0,1,0,die
14,39785205,台灣茗門茶業,100000,N,2013-06-04,2018-05-18,0,南投縣竹山鎮中崎里９鄰民生巷３５―７號,0,0,1,0,die
15,14617131,福田花莊,3000,N,2003-01-08,2018-09-20,0,南投縣竹山鎮延和里集山路３段５７５號,0,0,1,0,die
16,9231707,竹山滿意清潔社,10000,N,2005-11-29,2018-08-29,0,南投縣竹山鎮雲林里公所路１３７號,0,0,1,1,die
17,53498751,聖東種苗有限公司,8000000,N,2011-07-26,2018-09-19,0,南投縣草屯鎮北勢里玉屏巷２８－２９號,0,0,0,1,die
18,21824655,松柏園藝社,360000,N,2005-04-20,2018-05-22,0,南投縣草屯鎮南埔里中正路２３３―８３號１樓,0,0,1,0,die
19,61949884,見生農藥行,3000,N,1984-04-18,2017-12-15,0,南投縣草屯鎮山腳里正榮街１５８號,0,0,1,0,die
20,21477331,如祥園藝工程行,200000,N,2005-03-01,2018-06-29,0,南投縣草屯鎮平林里９鄰平學路３４５號,0,0,0,1,die
21,22567818,隆詮企業有限公司,6000000,N,1987-08-05,2018-11-01,0,南投縣草屯鎮新庄里２１鄰史舘路４２１巷７弄２號,0,0,0,1,die
22,28562229,介美麗花卉進出口有限公司,5000000,N,2007-01-17,2018-07-16,0,南投縣草屯鎮新豐里１４鄰稻香路５９－２號１Ｆ,0,0,0,1,die
23,38972840,築園造景園藝社,200000,N,2014-10-24,2018-07-01,0,南投縣魚池鄉新城村通文巷５２－１６號１樓,0,0,1,0,die
24,54507808,仟崧事業有限公司,600000,Y,2013-07-18,2019-01-01,0,南投縣魚池鄉魚池村瓊文巷３６－３０號,0,0,1,1,die
25,45547271,弘奇園藝清潔社,480000,N,2007-10-24,2019-01-18,0,南投縣鹿谷鄉瑞田村１０鄰集連巷４―８號,0,0,0,1,die
26,60212605,順貹實業股份有限公司,1000000,N,1986-08-01,2019-01-01,0,嘉義市東 區太平里民權路１１６―１號８樓,0,0,1,0,die
27,53642566,綠色方舟景觀有限公司,6000000,N,2011-12-06,2018-04-19,0,嘉義市東 區長竹里大雅路２段２９６號１樓,0,0,0,1,die
28,39709170,家孚企業社,200000,N,2012-11-20,2018-03-29,0,嘉義市西 區福全里北港路２４８－１５號４樓之２,0,0,0,1,die
29,18291923,吉野企業社,3000000,N,2001-12-18,2018-06-29,0,嘉義市西 區竹圍里德惠街３９號５樓之５,0,0,1,1,die
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19764,21338036,聖光藝術企業社,100000,N,2005-03-08,n,0,高雄市鼓山區明誠里民強街２３７號１樓,0,0,1,0,close
19765,19929387,日盛花店,5000,N,1997-02-04,n,0,高雄市鼓山區明誠里裕誠路１０２３號,0,0,1,0,close
19766,19929422,統一花卉行,5000,N,1997-02-04,n,0,高雄市鼓山區明誠里裕誠路１０２３號,0,0,1,0,close
19767,19929437,振富花卉行,5000,N,1997-02-04,n,0,高雄市鼓山區明誠里裕誠路１０２３號,0,0,1,0,close
19768,19929443,振榮鮮花,5000,N,1997-02-04,n,0,高雄市鼓山區明誠里裕誠路１０２３號,0,0,1,0,close
19769,19929458,西村花藝行,5000,N,1997-02-04,n,0,高雄市鼓山區明誠里裕誠路１０２３號,0,0,1,0,close
19770,18447334,二嫂花藝設計坊,3000,N,2000-12-07,n,0,高雄市鼓山區明誠里裕誠路１０２７號１樓,0,0,1,0,close
19771,21308286,阿英花卉行,30000,N,2004-11-08,n,0,高雄市鼓山區明誠里裕誠路１０３３號,0,0,1,0,close
19772,13648902,長林鮮花苑,3000,N,2001-07-19,n,0,高雄市鼓山區明誠里裕誠路１０６５號,0,0,1,0,close
19773,92032599,貴蘭園藝花卉,30000,N,1994-10-11,n,0,高雄市鼓山區樹德里鼓山二路２１８巷４７號,0,0,1,0,close
19774,81862196,龍品商行,200000,N,1995-06-23,n,0,高雄市鼓山區翠華路２７０號,0,0,1,0,close
19775,7828053,和昌花園,3000,N,1993-08-10,n,0,高雄市鼓山區翠華路３０６之１號,0,0,1,0,close
19776,14571352,陸豐企業行,200000,N,2002-04-24,n,0,高雄市鼓山區裕興里華寧路１４３號５樓,0,0,0,1,close
19777,20213311,東松花店,30000,N,1997-05-02,n,0,高雄市鼓山區裕興里華泰路１８３號,0,0,1,0,close
19778,78714539,愈豐鮮花店,3000,N,1992-09-09,n,0,高雄市鼓山區長安街２９之４號１樓,0,0,1,0,close
19779,19227772,東興文具花坊,30000,N,1999-01-27,n,0,高雄市鼓山區雄峰里九如四路１９９１巷１弄１２號１樓,0,0,1,0,close
19780,6852358,日月鮮花店,5000,N,1991-06-03,n,0,高雄市鼓山區青雲街５６號,0,0,1,0,close
19781,82103433,愛友企業社,3000,N,1983-12-15,n,0,高雄市鼓山區麗興里鼓元街２０巷１３弄１號,0,0,1,0,close
19782,7827028,春菊鮮花店,5000,N,1993-03-24,n,0,高雄市鼓山區麗興里鼓山一路１０號１樓,0,0,1,0,close
19783,86664012,川敏國際股份有限公司,5000000,N,1992-06-16,n,0,高雄市鼓山區鼓山二路２４６巷２４號,0,0,1,0,close
19784,19218773,九九花坊,10000,N,1998-12-04,n,0,高雄市鼓山區龍井里鼓山三路２３―２號,0,0,1,0,close
19785,25945814,愛上巴里島,3000,N,2009-07-28,n,0,高雄市鼓山區龍子里博愛一路４３３號,0,0,1,0,close
19786,25907121,大欉園藝社,200000,N,2009-12-15,n,0,高雄市鼓山區龍子里博愛一路４３３號１樓,0,0,1,1,close
19787,36907540,家鈴養生農場,50000,N,2012-06-04,n,0,高雄市鼓山區龍子里大順一路１０４１巷３號２５樓之３,0,0,1,1,close
19788,21378326,北高雄水族館,300000,N,2005-07-07,n,0,高雄市鼓山區龍子里明誠三路７２９號,0,0,1,0,close
19789,81866756,景山園藝行,10000,N,1994-05-12,n,0,高雄市鼓山區龍水里中華一路１７２號,0,0,1,0,close
19790,57974299,綠川園藝行,50000,N,2007-07-02,n,0,高雄市鼓山區龍水里美術北三路９３號１３樓,0,0,1,1,close
19791,14831499,創世咖啡館,10000,N,2002-06-19,n,0,高雄市鼓山區龍水里美術北五街５９巷２６號１樓,0,1,1,0,close
19792,21389920,創世咖啡館美術館門市部,0,N,2005-08-05,n,0,高雄市鼓山區龍水里美術館路８０號,0,0,1,0,close
19793,24660558,和景有限公司,200000,N,2014-08-29,n,0,高雄市鼓山區龍水里青海路２７７號,0,0,1,1,close

In [3]:
# sd = df["設立日期"]
df = df.replace("n","2019-04-02")
df["設立日期"] = pd.to_datetime(df["設立日期"])
df["停業日期"] = pd.to_datetime(df["停業日期"])
# df["停業日期"] = pd.to_datetime(df["停業日期"]) 非日期會產生錯誤
# d_s = df["設立日期"]
df

,統一編號,營業人名稱,資本額,使用統一發票,設立日期,停業日期,組織別名稱,營業地址,殯葬,餐廳,花卉相關銷售,花卉栽種,目前狀態
0,94920851,保証責任南投縣和興合作農場,200000,N,2003-05-26,2018-07-12,0,南投縣中寮鄉和興村００８鄰永樂路１４３號,0,0,1,0,die
1,45651105,祥林園藝,90000,N,2008-04-11,2019-01-01,0,南投縣仁愛鄉南豐村１２鄰中正路１１８－３號,0,0,1,0,die
2,80590886,松濤園企業有限公司,1200000,N,2003-11-19,2018-06-01,0,南投縣南投市光輝里省府路７８號,0,0,1,1,die
3,14606346,百合園藝,50000,N,2002-09-16,2017-09-30,0,南投縣南投市南投里２鄰民權街８７號,0,0,1,0,die
4,39919339,中興蘭園,200000,N,2013-12-10,2017-09-11,0,南投縣南投市營北里仁義南路３４巷７號,0,0,1,0,die
5,19258866,松柏林園藝綠化土木工程行,3000,N,2000-11-06,2018-08-21,0,南投縣國姓鄉北港村北原路６８－２號,0,0,0,1,die
6,78121043,文通林業行,600000,Y,1997-06-20,2019-02-28,0,南投縣埔里鎮北安里三民路２６巷１０號１樓,0,0,1,1,die
7,10920667,尚宏山業行,6000000,N,2010-12-23,2019-01-30,0,南投縣埔里鎮北安里１７鄰和平東路５３６號１樓,0,0,1,0,die
8,80088169,順瓏農產有限公司,5000000,Y,2003-01-28,2019-02-01,0,南投縣埔里鎮北梅里１８鄰仁愛路５１１號,0,0,1,0,die
9,62164967,統裕行,4700000,N,1971-04-01,2018-06-30,0,南投縣埔里鎮同聲里光華街９５巷３號１樓,0,0,1,1,die
10,42742309,美宥美企業有限公司,1000000,N,2015-11-02,2018-08-21,0,南投縣埔里鎮泰安里民族街７８號１樓,0,0,1,0,die
11,53975780,宿山企業有限公司,500000,N,2012-08-22,2018-10-01,0,南投縣埔里鎮麒麟里過坑路７８號１樓,0,0,1,0,die
12,28316254,一家國際生活館有限公司,1000000,N,2006-05-17,2018-09-01,0,南投縣水里鄉北埔村１２鄰民族路１７１號１、２樓,0,0,1,0,die
13,9345048,太朴松濤園,200000,N,2006-04-24,2019-03-03,0,南投縣水里鄉永興村林朋巷１７８－３號,0,0,1,0,die
14,39785205,台灣茗門茶業,100000,N,2013-06-04,2018-05-18,0,南投縣竹山鎮中崎里９鄰民生巷３５―７號,0,0,1,0,die
15,14617131,福田花莊,3000,N,2003-01-08,2018-09-20,0,南投縣竹山鎮延和里集山路３段５７５號,0,0,1,0,die
16,9231707,竹山滿意清潔社,10000,N,2005-11-29,2018-08-29,0,南投縣竹山鎮雲林里公所路１３７號,0,0,1,1,die
17,53498751,聖東種苗有限公司,8000000,N,2011-07-26,2018-09-19,0,南投縣草屯鎮北勢里玉屏巷２８－２９號,0,0,0,1,die
18,21824655,松柏園藝社,360000,N,2005-04-20,2018-05-22,0,南投縣草屯鎮南埔里中正路２３３―８３號１樓,0,0,1,0,die
19,61949884,見生農藥行,3000,N,1984-04-18,2017-12-15,0,南投縣草屯鎮山腳里正榮街１５８號,0,0,1,0,die
20,21477331,如祥園藝工程行,200000,N,2005-03-01,2018-06-29,0,南投縣草屯鎮平林里９鄰平學路３４５號,0,0,0,1,die
21,22567818,隆詮企業有限公司,6000000,N,1987-08-05,2018-11-01,0,南投縣草屯鎮新庄里２１鄰史舘路４２１巷７弄２號,0,0,0,1,die
22,28562229,介美麗花卉進出口有限公司,5000000,N,2007-01-17,2018-07-16,0,南投縣草屯鎮新豐里１４鄰稻香路５９－２號１Ｆ,0,0,0,1,die
23,38972840,築園造景園藝社,200000,N,2014-10-24,2018-07-01,0,南投縣魚池鄉新城村通文巷５２－１６號１樓,0,0,1,0,die
24,54507808,仟崧事業有限公司,600000,Y,2013-07-18,2019-01-01,0,南投縣魚池鄉魚池村瓊文巷３６－３０號,0,0,1,1,die
25,45547271,弘奇園藝清潔社,480000,N,2007-10-24,2019-01-18,0,南投縣鹿谷鄉瑞田村１０鄰集連巷４―８號,0,0,0,1,die
26,60212605,順貹實業股份有限公司,1000000,N,1986-08-01,2019-01-01,0,嘉義市東 區太平里民權路１１６―１號８樓,0,0,1,0,die
27,53642566,綠色方舟景觀有限公司,6000000,N,2011-12-06,2018-04-19,0,嘉義市東 區長竹里大雅路２段２９６號１樓,0,0,0,1,die
28,39709170,家孚企業社,200000,N,2012-11-20,2018-03-29,0,嘉義市西 區福全里北港路２４８－１５號４樓之２,0,0,0,1,die
29,18291923,吉野企業社,3000000,N,2001-12-18,2018-06-29,0,嘉義市西 區竹圍里德惠街３９號５樓之５,0,0,1,1,die
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19764,21338036,聖光藝術企業社,100000,N,2005-03-08,2019-04-02,0,高雄市鼓山區明誠里民強街２３７號１樓,0,0,1,0,close
19765,19929387,日盛花店,5000,N,1997-02-04,2019-04-02,0,高雄市鼓山區明誠里裕誠路１０２３號,0,0,1,0,close
19766,19929422,統一花卉行,5000,N,1997-02-04,2019-04-02,0,高雄市鼓山區明誠里裕誠路１０２３號,0,0,1,0,close
19767,19929437,振富花卉行,5000,N,1997-02-04,2019-04-02,0,高雄市鼓山區明誠里裕誠路１０２３號,0,0,1,0,close
19768,19929443,振榮鮮花,5000,N,1997-02-04,2019-04-02,0,高雄市鼓山區明誠里裕誠路１０２３號,0,0,1,0,close
19769,19929458,西村花藝行,5000,N,1997-02-04,2019-04-02,0,高雄市鼓山區明誠里裕誠路１０２３號,0,0,1,0,close
19770,18447334,二嫂花藝設計坊,3000,N,2000-12-07,2019-04-02,0,高雄市鼓山區明誠里裕誠路１０２７號１樓,0,0,1,0,close
19771,21308286,阿英花卉行,30000,N,2004-11-08,2019-04-02,0,高雄市鼓山區明誠里裕誠路１０３３號,0,0,1,0,close
19772,13648902,長林鮮花苑,3000,N,2001-07-19,2019-04-02,0,高雄市鼓山區明誠里裕誠路１０６５號,0,0,1,0,close
19773,92032599,貴蘭園藝花卉,30000,N,1994-10-11,2019-04-02,0,高雄市鼓山區樹德里鼓山二路２１８巷４７號,0,0,1,0,close
19774,81862196,龍品商行,200000,N,1995-06-23,2019-04-02,0,高雄市鼓山區翠華路２７０號,0,0,1,0,close
19775,7828053,和昌花園,3000,N,1993-08-10,2019-04-02,0,高雄市鼓山區翠華路３０６之１號,0,0,1,0,close
19776,14571352,陸豐企業行,200000,N,2002-04-24,2019-04-02,0,高雄市鼓山區裕興里華寧路１４３號５樓,0,0,0,1,close
19777,20213311,東松花店,30000,N,1997-05-02,2019-04-02,0,高雄市鼓山區裕興里華泰路１８３號,0,0,1,0,close
19778,78714539,愈豐鮮花店,3000,N,1992-09-09,2019-04-02,0,高雄市鼓山區長安街２９之４號１樓,0,0,1,0,close
19779,19227772,東興文具花坊,30000,N,1999-01-27,2019-04-02,0,高雄市鼓山區雄峰里九如四路１９９１巷１弄１２號１樓,0,0,1,0,close
19780,6852358,日月鮮花店,5000,N,1991-06-03,2019-04-02,0,高雄市鼓山區青雲街５６號,0,0,1,0,close
19781,82103433,愛友企業社,3000,N,1983-12-15,2019-04-02,0,高雄市鼓山區麗興里鼓元街２０巷１３弄１號,0,0,1,0,close
19782,7827028,春菊鮮花店,5000,N,1993-03-24,2019-04-02,0,高雄市鼓山區麗興里鼓山一路１０號１樓,0,0,1,0,close
19783,86664012,川敏國際股份有限公司,5000000,N,1992-06-16,2019-04-02,0,高雄市鼓山區鼓山二路２４６巷２４號,0,0,1,0,close
19784,19218773,九九花坊,10000,N,1998-12-04,2019-04-02,0,高雄市鼓山區龍井里鼓山三路２３―２號,0,0,1,0,close
19785,25945814,愛上巴里島,3000,N,2009-07-28,2019-04-02,0,高雄市鼓山區龍子里博愛一路４３３號,0,0,1,0,close
19786,25907121,大欉園藝社,200000,N,2009-12-15,2019-04-02,0,高雄市鼓山區龍子里博愛一路４３３號１樓,0,0,1,1,close
19787,36907540,家鈴養生農場,50000,N,2012-06-04,2019-04-02,0,高雄市鼓山區龍子里大順一路１０４１巷３號２５樓之３,0,0,1,1,close
19788,21378326,北高雄水族館,300000,N,2005-07-07,2019-04-02,0,高雄市鼓山區龍子里明誠三路７２９號,0,0,1,0,close
19789,81866756,景山園藝行,10000,N,1994-05-12,2019-04-02,0,高雄市鼓山區龍水里中華一路１７２號,0,0,1,0,close
19790,57974299,綠川園藝行,50000,N,2007-07-02,2019-04-02,0,高雄市鼓山區龍水里美術北三路９３號１３樓,0,0,1,1,close
19791,14831499,創世咖啡館,10000,N,2002-06-19,2019-04-02,0,高雄市鼓山區龍水里美術北五街５９巷２６號１樓,0,1,1,0,close
19792,21389920,創世咖啡館美術館門市部,0,N,2005-08-05,2019-04-02,0,高雄市鼓山區龍水里美術館路８０號,0,0,1,0,close
19793,24660558,和景有限公司,200000,N,2014-08-29,2019-04-02,0,高雄市鼓山區龍水里青海路２７７號,0,0,1,1,close

In [4]:
# date > strd
#     strftime
# str > date
#     strptime
# date <>timetuple
#     timetuple
# datetime > date
#     date ()

In [5]:
from datetime import datetime, date, time
from datetime import timedelta
# d1 = d_s[0].date()
# test date() timedelta
d1 = timedelta(days= 1)
d_s = date(2014, 1, 1)
d_end = date(2019, 4, 1)
total_d = d_end - d_s
print(total_d.days)
d = d_s
for i in range(10):
    print(d)
    d = d + d1

1916
2014-01-01
2014-01-02
2014-01-03
2014-01-04
2014-01-05
2014-01-06
2014-01-07
2014-01-08
2014-01-09
2014-01-10

In [6]:
d_test = d_s = date(2014, 1, 1)
d_arr = np.array(df)
# d_arr
c = df.columns
for i in range(len(c)):
    print(i, c[i])

0 統一編號
1 營業人名稱
2 資本額
3 使用統一發票
4 設立日期
5 停業日期
6 組織別名稱
7 營業地址
8 殯葬
9 餐廳
10 花卉相關銷售
11 花卉栽種
12 目前狀態

In [7]:
d_op =d_arr[:,4]
d_cl =d_arr[:,5]
d_op = d_op.astype(np.datetime64).tolist()
d_cl = d_cl.astype(np.datetime64).tolist()

In [8]:
from time import time
t_date = date
d1 = timedelta(days= 1)
d_s = date(2014, 1, 1)
d_end = date(2019, 4, 1)
total_d = d_end - d_s
total_d = total_d.days
d = d_s
opdata = []
cdate = []
t1 = time()
# total_d = 3
for j in range(total_d):
#     print(d)
    ontime_open=[]
    data_c = len(d_op)
#     data_c = 3
    for i in range(data_c):
        b_op = d_op[i].date() < d
        b_not_cl = d_cl[i].date() > d
        ontime_open.append(bool(b_op*b_not_cl))
#     print(b_op*1, b_not_cl*1, b_op*b_not_cl, d_op[i].date(), d_cl[i].date())
    opdata.append(ontime_open)
    cdate.append(d)
#     print(ontime_open)
    d = d + d1
print(d)
print(time()-t1)

2019-04-01
26.391669273376465

In [9]:
# d_arr[bool(opdata[0]*d_arr[:,8]),:]
# d_arr[(opdata[0]*d_arr[:,8]).astype(bool),:]
# 0 統一編號 1 營業人名稱 2 資本額(int) 3 使用統一發票(str) 4 設立日 
# 5 停業日期 6 組織別名稱 7 營業地址 8 殯葬 9 餐廳 10 花卉銷售
# 11 花卉栽種 12 目前狀態
test = d_arr[0, :]
test

array([94920851, '保証責任南投縣和興合作農場', 200000, 'N',
       Timestamp('2003-05-26 00:00:00'), Timestamp('2018-07-12 00:00:00'),
       '0', '南投縣中寮鄉和興村００８鄰永樂路１４３號', 0, 0, 1, 0, 'die'], dtype=object)

In [10]:
# 已開 * 有開統一發票 * 8 殯葬 9 餐廳 10 花卉銷售 # 11 花卉栽種
c_with_uni_date=[]
for i in range(total_d):
    date = cdate[i]
    b_op = opdata[i]*1 # 該時間點已開張的條件
    b_uni = (d_arr[:, 3]=="Y")*1
    result = []
    result.append(date)
    for c in range(8,11+1):
        b_c = (d_arr[:, c]==1)*1
        b = (b_op*b_uni*b_c).astype(bool)
        result.append(len(d_arr[b, :]))
    c_with_uni_date.append(result)

In [11]:
c_with_uni_date

[[datetime.date(2014, 1, 1), 198, 48, 2440, 1426],
 [datetime.date(2014, 1, 2), 198, 48, 2440, 1426],
 [datetime.date(2014, 1, 3), 198, 48, 2440, 1427],
 [datetime.date(2014, 1, 4), 198, 48, 2442, 1427],
 [datetime.date(2014, 1, 5), 198, 48, 2442, 1427],
 [datetime.date(2014, 1, 6), 198, 48, 2442, 1427],
 [datetime.date(2014, 1, 7), 198, 48, 2442, 1427],
 [datetime.date(2014, 1, 8), 198, 48, 2442, 1427],
 [datetime.date(2014, 1, 9), 198, 48, 2443, 1427],
 [datetime.date(2014, 1, 10), 198, 48, 2443, 1427],
 [datetime.date(2014, 1, 11), 198, 48, 2443, 1427],
 [datetime.date(2014, 1, 12), 198, 48, 2443, 1427],
 [datetime.date(2014, 1, 13), 198, 48, 2443, 1427],
 [datetime.date(2014, 1, 14), 198, 48, 2443, 1427],
 [datetime.date(2014, 1, 15), 198, 48, 2444, 1429],
 [datetime.date(2014, 1, 16), 198, 48, 2446, 1429],
 [datetime.date(2014, 1, 17), 198, 48, 2448, 1429],
 [datetime.date(2014, 1, 18), 198, 48, 2448, 1430],
 [datetime.date(2014, 1, 19), 198, 48, 2448, 1430],
 [datetime.date(2014, 1, 20), 198, 48, 2448, 1430],
 [datetime.date(2014, 1, 21), 198, 48, 2449, 1430],
 [datetime.date(2014, 1, 22), 198, 48, 2449, 1430],
 [datetime.date(2014, 1, 23), 198, 48, 2450, 1431],
 [datetime.date(2014, 1, 24), 198, 48, 2451, 1431],
 [datetime.date(2014, 1, 25), 198, 48, 2452, 1431],
 [datetime.date(2014, 1, 26), 198, 48, 2452, 1431],
 [datetime.date(2014, 1, 27), 198, 48, 2452, 1431],
 [datetime.date(2014, 1, 28), 198, 48, 2452, 1431],
 [datetime.date(2014, 1, 29), 198, 48, 2452, 1431],
 [datetime.date(2014, 1, 30), 198, 48, 2453, 1431],
 [datetime.date(2014, 1, 31), 198, 48, 2453, 1431],
 [datetime.date(2014, 2, 1), 198, 48, 2453, 1431],
 [datetime.date(2014, 2, 2), 198, 48, 2453, 1431],
 [datetime.date(2014, 2, 3), 198, 48, 2453, 1431],
 [datetime.date(2014, 2, 4), 198, 48, 2453, 1431],
 [datetime.date(2014, 2, 5), 198, 48, 2453, 1431],
 [datetime.date(2014, 2, 6), 198, 48, 2455, 1432],
 [datetime.date(2014, 2, 7), 198, 48, 2456, 1432],
 [datetime.date(2014, 2, 8), 198, 48, 2456, 1432],
 [datetime.date(2014, 2, 9), 198, 48, 2456, 1432],
 [datetime.date(2014, 2, 10), 198, 48, 2456, 1432],
 [datetime.date(2014, 2, 11), 198, 48, 2456, 1432],
 [datetime.date(2014, 2, 12), 198, 48, 2457, 1433],
 [datetime.date(2014, 2, 13), 198, 48, 2457, 1433],
 [datetime.date(2014, 2, 14), 198, 48, 2457, 1433],
 [datetime.date(2014, 2, 15), 198, 48, 2457, 1433],
 [datetime.date(2014, 2, 16), 198, 48, 2457, 1433],
 [datetime.date(2014, 2, 17), 198, 48, 2457, 1433],
 [datetime.date(2014, 2, 18), 198, 48, 2457, 1434],
 [datetime.date(2014, 2, 19), 198, 48, 2458, 1434],
 [datetime.date(2014, 2, 20), 198, 48, 2458, 1434],
 [datetime.date(2014, 2, 21), 198, 48, 2458, 1434],
 [datetime.date(2014, 2, 22), 198, 48, 2458, 1434],
 [datetime.date(2014, 2, 23), 198, 48, 2458, 1434],
 [datetime.date(2014, 2, 24), 198, 48, 2458, 1434],
 [datetime.date(2014, 2, 25), 198, 48, 2458, 1434],
 [datetime.date(2014, 2, 26), 198, 48, 2458, 1434],
 [datetime.date(2014, 2, 27), 198, 48, 2458, 1434],
 [datetime.date(2014, 2, 28), 198, 48, 2459, 1434],
 [datetime.date(2014, 3, 1), 198, 48, 2459, 1434],
 [datetime.date(2014, 3, 2), 198, 48, 2459, 1434],
 [datetime.date(2014, 3, 3), 198, 48, 2459, 1434],
 [datetime.date(2014, 3, 4), 198, 48, 2459, 1434],
 [datetime.date(2014, 3, 5), 198, 48, 2459, 1434],
 [datetime.date(2014, 3, 6), 198, 48, 2460, 1434],
 [datetime.date(2014, 3, 7), 198, 48, 2462, 1435],
 [datetime.date(2014, 3, 8), 199, 48, 2463, 1435],
 [datetime.date(2014, 3, 9), 199, 48, 2463, 1435],
 [datetime.date(2014, 3, 10), 199, 48, 2463, 1435],
 [datetime.date(2014, 3, 11), 199, 48, 2463, 1435],
 [datetime.date(2014, 3, 12), 199, 48, 2465, 1437],
 [datetime.date(2014, 3, 13), 199, 48, 2467, 1438],
 [datetime.date(2014, 3, 14), 199, 48, 2468, 1438],
 [datetime.date(2014, 3, 15), 199, 48, 2468, 1438],
 [datetime.date(2014, 3, 16), 199, 48, 2468, 1438],
 [datetime.date(2014, 3, 17), 199, 48, 2468, 1438],
 [datetime.date(2014, 3, 18), 199, 48, 2469, 1438],
 [datetime.date(2014, 3, 19), 199, 48, 2469, 1438],
 [datetime.date(2014, 3, 20), 199, 48, 2470, 1438],
 [datetime.date(2014, 3, 21), 199, 48, 2471, 1438],
 [datetime.date(2014, 3, 22), 199, 48, 2471, 1438],
 [datetime.date(2014, 3, 23), 199, 48, 2471, 1438],
 [datetime.date(2014, 3, 24), 199, 48, 2471, 1438],
 [datetime.date(2014, 3, 25), 199, 48, 2472, 1439],
 [datetime.date(2014, 3, 26), 199, 48, 2474, 1440],
 [datetime.date(2014, 3, 27), 199, 48, 2476, 1440],
 [datetime.date(2014, 3, 28), 199, 48, 2476, 1440],
 [datetime.date(2014, 3, 29), 199, 48, 2477, 1440],
 [datetime.date(2014, 3, 30), 199, 48, 2477, 1440],
 [datetime.date(2014, 3, 31), 199, 48, 2477, 1440],
 [datetime.date(2014, 4, 1), 199, 48, 2478, 1441],
 [datetime.date(2014, 4, 2), 199, 48, 2480, 1443],
 [datetime.date(2014, 4, 3), 199, 48, 2481, 1445],
 [datetime.date(2014, 4, 4), 199, 48, 2482, 1445],
 [datetime.date(2014, 4, 5), 199, 48, 2482, 1445],
 [datetime.date(2014, 4, 6), 199, 48, 2482, 1445],
 [datetime.date(2014, 4, 7), 199, 48, 2482, 1445],
 [datetime.date(2014, 4, 8), 199, 48, 2484, 1447],
 [datetime.date(2014, 4, 9), 199, 48, 2485, 1447],
 [datetime.date(2014, 4, 10), 199, 48, 2487, 1448],
 [datetime.date(2014, 4, 11), 199, 48, 2487, 1448],
 [datetime.date(2014, 4, 12), 199, 48, 2488, 1448],
 [datetime.date(2014, 4, 13), 199, 48, 2488, 1448],
 [datetime.date(2014, 4, 14), 199, 48, 2488, 1448],
 [datetime.date(2014, 4, 15), 199, 48, 2489, 1448],
 [datetime.date(2014, 4, 16), 199, 48, 2491, 1450],
 [datetime.date(2014, 4, 17), 199, 48, 2491, 1450],
 [datetime.date(2014, 4, 18), 199, 48, 2492, 1450],
 [datetime.date(2014, 4, 19), 199, 48, 2494, 1451],
 [datetime.date(2014, 4, 20), 199, 48, 2494, 1451],
 [datetime.date(2014, 4, 21), 199, 48, 2494, 1451],
 [datetime.date(2014, 4, 22), 199, 48, 2494, 1451],
 [datetime.date(2014, 4, 23), 199, 49, 2495, 1451],
 [datetime.date(2014, 4, 24), 200, 49, 2496, 1451],
 [datetime.date(2014, 4, 25), 200, 49, 2497, 1451],
 [datetime.date(2014, 4, 26), 200, 49, 2497, 1452],
 [datetime.date(2014, 4, 27), 200, 49, 2497, 1452],
 [datetime.date(2014, 4, 28), 200, 49, 2497, 1452],
 [datetime.date(2014, 4, 29), 201, 50, 2499, 1453],
 [datetime.date(2014, 4, 30), 201, 50, 2500, 1455],
 [datetime.date(2014, 5, 1), 201, 50, 2501, 1456],
 [datetime.date(2014, 5, 2), 201, 50, 2502, 1457],
 [datetime.date(2014, 5, 3), 201, 50, 2503, 1457],
 [datetime.date(2014, 5, 4), 201, 50, 2503, 1457],
 [datetime.date(2014, 5, 5), 201, 50, 2503, 1457],
 [datetime.date(2014, 5, 6), 201, 50, 2503, 1458],
 [datetime.date(2014, 5, 7), 201, 50, 2503, 1458],
 [datetime.date(2014, 5, 8), 201, 50, 2503, 1459],
 [datetime.date(2014, 5, 9), 201, 50, 2503, 1459],
 [datetime.date(2014, 5, 10), 201, 50, 2503, 1459],
 [datetime.date(2014, 5, 11), 201, 50, 2503, 1459],
 [datetime.date(2014, 5, 12), 201, 50, 2503, 1459],
 [datetime.date(2014, 5, 13), 201, 50, 2503, 1459],
 [datetime.date(2014, 5, 14), 201, 50, 2503, 1459],
 [datetime.date(2014, 5, 15), 201, 50, 2503, 1459],
 [datetime.date(2014, 5, 16), 201, 50, 2504, 1460],
 [datetime.date(2014, 5, 17), 201, 50, 2505, 1460],
 [datetime.date(2014, 5, 18), 201, 50, 2505, 1460],
 [datetime.date(2014, 5, 19), 201, 50, 2505, 1460],
 [datetime.date(2014, 5, 20), 201, 50, 2505, 1460],
 [datetime.date(2014, 5, 21), 201, 50, 2505, 1460],
 [datetime.date(2014, 5, 22), 201, 50, 2506, 1460],
 [datetime.date(2014, 5, 23), 201, 50, 2506, 1460],
 [datetime.date(2014, 5, 24), 201, 50, 2507, 1460],
 [datetime.date(2014, 5, 25), 201, 50, 2507, 1460],
 [datetime.date(2014, 5, 26), 201, 50, 2507, 1460],
 [datetime.date(2014, 5, 27), 201, 50, 2508, 1461],
 [datetime.date(2014, 5, 28), 201, 50, 2509, 1461],
 [datetime.date(2014, 5, 29), 201, 50, 2510, 1461],
 [datetime.date(2014, 5, 30), 201, 50, 2511, 1462],
 [datetime.date(2014, 5, 31), 201, 50, 2511, 1462],
 [datetime.date(2014, 6, 1), 201, 50, 2511, 1462],
 [datetime.date(2014, 6, 2), 201, 50, 2511, 1462],
 [datetime.date(2014, 6, 3), 201, 50, 2511, 1462],
 [datetime.date(2014, 6, 4), 201, 50, 2511, 1462],
 [datetime.date(2014, 6, 5), 201, 50, 2511, 1462],
 [datetime.date(2014, 6, 6), 201, 50, 2512, 1464],
 [datetime.date(2014, 6, 7), 201, 50, 2512, 1464],
 [datetime.date(2014, 6, 8), 201, 50, 2512, 1464],
 [datetime.date(2014, 6, 9), 201, 50, 2512, 1464],
 [datetime.date(2014, 6, 10), 201, 50, 2514, 1464],
 [datetime.date(2014, 6, 11), 202, 50, 2517, 1465],
 [datetime.date(2014, 6, 12), 202, 50, 2517, 1466],
 [datetime.date(2014, 6, 13), 202, 50, 2518, 1466],
 [datetime.date(2014, 6, 14), 202, 50, 2518, 1467],
 [datetime.date(2014, 6, 15), 202, 50, 2518, 1467],
 [datetime.date(2014, 6, 16), 202, 50, 2518, 1467],
 [datetime.date(2014, 6, 17), 203, 50, 2520, 1468],
 [datetime.date(2014, 6, 18), 203, 50, 2521, 1469],
 [datetime.date(2014, 6, 19), 203, 50, 2523, 1469],
 [datetime.date(2014, 6, 20), 203, 50, 2523, 1469],
 [datetime.date(2014, 6, 21), 203, 50, 2523, 1469],
 [datetime.date(2014, 6, 22), 203, 50, 2523, 1469],
 [datetime.date(2014, 6, 23), 203, 50, 2523, 1469],
 [datetime.date(2014, 6, 24), 203, 50, 2524, 1471],
 [datetime.date(2014, 6, 25), 203, 50, 2524, 1472],
 [datetime.date(2014, 6, 26), 203, 50, 2524, 1472],
 [datetime.date(2014, 6, 27), 203, 50, 2524, 1472],
 [datetime.date(2014, 6, 28), 203, 50, 2525, 1473],
 [datetime.date(2014, 6, 29), 203, 50, 2525, 1473],
 [datetime.date(2014, 6, 30), 203, 50, 2525, 1473],
 [datetime.date(2014, 7, 1), 203, 50, 2525, 1473],
 [datetime.date(2014, 7, 2), 203, 50, 2526, 1474],
 [datetime.date(2014, 7, 3), 203, 50, 2527, 1475],
 [datetime.date(2014, 7, 4), 203, 50, 2528, 1475],
 [datetime.date(2014, 7, 5), 203, 50, 2529, 1476],
 [datetime.date(2014, 7, 6), 203, 50, 2529, 1476],
 [datetime.date(2014, 7, 7), 203, 50, 2529, 1476],
 [datetime.date(2014, 7, 8), 203, 50, 2529, 1476],
 [datetime.date(2014, 7, 9), 203, 50, 2529, 1476],
 [datetime.date(2014, 7, 10), 204, 50, 2531, 1476],
 [datetime.date(2014, 7, 11), 204, 50, 2532, 1476],
 [datetime.date(2014, 7, 12), 204, 50, 2532, 1476],
 [datetime.date(2014, 7, 13), 204, 50, 2532, 1476],
 [datetime.date(2014, 7, 14), 204, 50, 2532, 1476],
 [datetime.date(2014, 7, 15), 204, 50, 2532, 1476],
 [datetime.date(2014, 7, 16), 204, 50, 2534, 1476],
 [datetime.date(2014, 7, 17), 204, 50, 2534, 1476],
 [datetime.date(2014, 7, 18), 204, 50, 2535, 1476],
 [datetime.date(2014, 7, 19), 204, 50, 2535, 1476],
 [datetime.date(2014, 7, 20), 204, 50, 2535, 1476],
 [datetime.date(2014, 7, 21), 204, 50, 2535, 1476],
 [datetime.date(2014, 7, 22), 204, 50, 2535, 1476],
 [datetime.date(2014, 7, 23), 204, 50, 2535, 1476],
 [datetime.date(2014, 7, 24), 204, 50, 2535, 1476],
 [datetime.date(2014, 7, 25), 204, 50, 2535, 1476],
 [datetime.date(2014, 7, 26), 204, 50, 2535, 1476],
 [datetime.date(2014, 7, 27), 204, 50, 2535, 1476],
 [datetime.date(2014, 7, 28), 204, 50, 2535, 1476],
 [datetime.date(2014, 7, 29), 204, 50, 2535, 1476],
 [datetime.date(2014, 7, 30), 205, 50, 2537, 1477],
 [datetime.date(2014, 7, 31), 205, 50, 2537, 1477],
 [datetime.date(2014, 8, 1), 205, 50, 2537, 1477],
 [datetime.date(2014, 8, 2), 205, 50, 2540, 1479],
 [datetime.date(2014, 8, 3), 205, 50, 2540, 1479],
 [datetime.date(2014, 8, 4), 205, 50, 2540, 1479],
 [datetime.date(2014, 8, 5), 205, 50, 2540, 1479],
 [datetime.date(2014, 8, 6), 205, 50, 2540, 1479],
 [datetime.date(2014, 8, 7), 205, 50, 2541, 1480],
 [datetime.date(2014, 8, 8), 205, 50, 2542, 1480],
 [datetime.date(2014, 8, 9), 205, 50, 2543, 1480],
 [datetime.date(2014, 8, 10), 205, 50, 2543, 1480],
 [datetime.date(2014, 8, 11), 205, 50, 2543, 1480],
 [datetime.date(2014, 8, 12), 205, 50, 2543, 1480],
 [datetime.date(2014, 8, 13), 205, 50, 2544, 1480],
 [datetime.date(2014, 8, 14), 205, 50, 2544, 1481],
 [datetime.date(2014, 8, 15), 205, 50, 2545, 1481],
 [datetime.date(2014, 8, 16), 205, 50, 2546, 1482],
 [datetime.date(2014, 8, 17), 205, 50, 2546, 1482],
 [datetime.date(2014, 8, 18), 205, 50, 2546, 1482],
 [datetime.date(2014, 8, 19), 205, 50, 2546, 1482],
 [datetime.date(2014, 8, 20), 205, 50, 2547, 1482],
 [datetime.date(2014, 8, 21), 205, 50, 2547, 1482],
 [datetime.date(2014, 8, 22), 205, 50, 2547, 1482],
 [datetime.date(2014, 8, 23), 205, 50, 2548, 1483],
 [datetime.date(2014, 8, 24), 205, 50, 2548, 1483],
 [datetime.date(2014, 8, 25), 205, 50, 2548, 1483],
 [datetime.date(2014, 8, 26), 205, 50, 2550, 1485],
 [datetime.date(2014, 8, 27), 205, 50, 2550, 1485],
 [datetime.date(2014, 8, 28), 205, 50, 2550, 1485],
 [datetime.date(2014, 8, 29), 205, 50, 2552, 1486],
 [datetime.date(2014, 8, 30), 205, 50, 2552, 1487],
 [datetime.date(2014, 8, 31), 205, 50, 2552, 1487],
 [datetime.date(2014, 9, 1), 205, 50, 2552, 1487],
 [datetime.date(2014, 9, 2), 205, 50, 2553, 1487],
 [datetime.date(2014, 9, 3), 205, 50, 2554, 1488],
 [datetime.date(2014, 9, 4), 205, 50, 2555, 1488],
 [datetime.date(2014, 9, 5), 205, 50, 2555, 1488],
 [datetime.date(2014, 9, 6), 205, 50, 2555, 1488],
 [datetime.date(2014, 9, 7), 205, 50, 2555, 1488],
 [datetime.date(2014, 9, 8), 205, 50, 2555, 1488],
 [datetime.date(2014, 9, 9), 205, 50, 2555, 1488],
 [datetime.date(2014, 9, 10), 205, 50, 2555, 1488],
 [datetime.date(2014, 9, 11), 205, 50, 2556, 1488],
 [datetime.date(2014, 9, 12), 205, 50, 2556, 1490],
 [datetime.date(2014, 9, 13), 205, 50, 2557, 1490],
 [datetime.date(2014, 9, 14), 205, 50, 2557, 1490],
 [datetime.date(2014, 9, 15), 205, 50, 2557, 1490],
 [datetime.date(2014, 9, 16), 205, 50, 2557, 1490],
 [datetime.date(2014, 9, 17), 205, 50, 2557, 1490],
 [datetime.date(2014, 9, 18), 206, 50, 2558, 1490],
 [datetime.date(2014, 9, 19), 207, 50, 2559, 1490],
 [datetime.date(2014, 9, 20), 207, 50, 2560, 1490],
 [datetime.date(2014, 9, 21), 207, 50, 2560, 1490],
 [datetime.date(2014, 9, 22), 207, 50, 2560, 1490],
 [datetime.date(2014, 9, 23), 207, 50, 2561, 1490],
 [datetime.date(2014, 9, 24), 207, 50, 2561, 1490],
 [datetime.date(2014, 9, 25), 207, 50, 2564, 1490],
 [datetime.date(2014, 9, 26), 208, 50, 2565, 1490],
 [datetime.date(2014, 9, 27), 208, 50, 2567, 1491],
 [datetime.date(2014, 9, 28), 208, 50, 2567, 1491],
 [datetime.date(2014, 9, 29), 208, 50, 2567, 1491],
 [datetime.date(2014, 9, 30), 208, 50, 2567, 1491],
 [datetime.date(2014, 10, 1), 209, 50, 2569, 1493],
 [datetime.date(2014, 10, 2), 209, 50, 2570, 1495],
 [datetime.date(2014, 10, 3), 209, 50, 2570, 1496],
 [datetime.date(2014, 10, 4), 209, 50, 2570, 1496],
 [datetime.date(2014, 10, 5), 209, 50, 2570, 1496],
 [datetime.date(2014, 10, 6), 209, 50, 2570, 1496],
 [datetime.date(2014, 10, 7), 209, 50, 2571, 1496],
 [datetime.date(2014, 10, 8), 209, 50, 2571, 1496],
 [datetime.date(2014, 10, 9), 209, 50, 2572, 1497],
 [datetime.date(2014, 10, 10), 209, 50, 2574, 1498],
 [datetime.date(2014, 10, 11), 209, 50, 2574, 1498],
 [datetime.date(2014, 10, 12), 209, 50, 2574, 1498],
 [datetime.date(2014, 10, 13), 209, 50, 2574, 1498],
 [datetime.date(2014, 10, 14), 209, 50, 2574, 1498],
 [datetime.date(2014, 10, 15), 209, 50, 2575, 1498],
 [datetime.date(2014, 10, 16), 210, 50, 2577, 1499],
 [datetime.date(2014, 10, 17), 210, 50, 2578, 1499],
 [datetime.date(2014, 10, 18), 210, 50, 2578, 1500],
 [datetime.date(2014, 10, 19), 210, 50, 2578, 1500],
 [datetime.date(2014, 10, 20), 210, 50, 2578, 1500],
 [datetime.date(2014, 10, 21), 210, 50, 2579, 1502],
 [datetime.date(2014, 10, 22), 210, 50, 2579, 1502],
 [datetime.date(2014, 10, 23), 210, 50, 2580, 1502],
 [datetime.date(2014, 10, 24), 210, 50, 2581, 1502],
 [datetime.date(2014, 10, 25), 210, 50, 2581, 1502],
 [datetime.date(2014, 10, 26), 210, 50, 2581, 1502],
 [datetime.date(2014, 10, 27), 210, 50, 2581, 1502],
 [datetime.date(2014, 10, 28), 210, 50, 2582, 1502],
 [datetime.date(2014, 10, 29), 210, 50, 2582, 1502],
 [datetime.date(2014, 10, 30), 210, 50, 2583, 1503],
 [datetime.date(2014, 10, 31), 210, 50, 2583, 1503],
 [datetime.date(2014, 11, 1), 210, 50, 2583, 1503],
 [datetime.date(2014, 11, 2), 210, 50, 2583, 1503],
 [datetime.date(2014, 11, 3), 210, 50, 2583, 1503],
 [datetime.date(2014, 11, 4), 210, 50, 2584, 1503],
 [datetime.date(2014, 11, 5), 210, 50, 2586, 1504],
 [datetime.date(2014, 11, 6), 210, 51, 2587, 1504],
 [datetime.date(2014, 11, 7), 211, 51, 2590, 1504],
 [datetime.date(2014, 11, 8), 211, 51, 2590, 1504],
 [datetime.date(2014, 11, 9), 211, 51, 2590, 1504],
 [datetime.date(2014, 11, 10), 211, 51, 2590, 1504],
 [datetime.date(2014, 11, 11), 211, 51, 2590, 1504],
 [datetime.date(2014, 11, 12), 211, 51, 2591, 1507],
 [datetime.date(2014, 11, 13), 211, 51, 2591, 1508],
 [datetime.date(2014, 11, 14), 211, 51, 2591, 1508],
 [datetime.date(2014, 11, 15), 212, 51, 2592, 1508],
 [datetime.date(2014, 11, 16), 212, 51, 2592, 1508],
 [datetime.date(2014, 11, 17), 212, 51, 2592, 1508],
 [datetime.date(2014, 11, 18), 212, 51, 2593, 1508],
 [datetime.date(2014, 11, 19), 212, 51, 2595, 1509],
 [datetime.date(2014, 11, 20), 212, 51, 2597, 1509],
 [datetime.date(2014, 11, 21), 212, 51, 2598, 1509],
 [datetime.date(2014, 11, 22), 212, 51, 2599, 1509],
 [datetime.date(2014, 11, 23), 212, 51, 2599, 1509],
 [datetime.date(2014, 11, 24), 212, 51, 2599, 1509],
 [datetime.date(2014, 11, 25), 212, 51, 2600, 1509],
 [datetime.date(2014, 11, 26), 212, 51, 2600, 1510],
 [datetime.date(2014, 11, 27), 212, 51, 2600, 1510],
 [datetime.date(2014, 11, 28), 212, 51, 2600, 1511],
 [datetime.date(2014, 11, 29), 212, 51, 2600, 1511],
 [datetime.date(2014, 11, 30), 212, 51, 2600, 1511],
 [datetime.date(2014, 12, 1), 212, 51, 2600, 1511],
 [datetime.date(2014, 12, 2), 212, 51, 2601, 1512],
 [datetime.date(2014, 12, 3), 212, 51, 2601, 1512],
 [datetime.date(2014, 12, 4), 212, 51, 2601, 1512],
 [datetime.date(2014, 12, 5), 212, 51, 2603, 1512],
 [datetime.date(2014, 12, 6), 212, 51, 2604, 1512],
 [datetime.date(2014, 12, 7), 212, 51, 2604, 1512],
 [datetime.date(2014, 12, 8), 212, 51, 2604, 1512],
 [datetime.date(2014, 12, 9), 213, 51, 2605, 1513],
 [datetime.date(2014, 12, 10), 213, 51, 2606, 1513],
 [datetime.date(2014, 12, 11), 214, 51, 2607, 1513],
 [datetime.date(2014, 12, 12), 214, 51, 2609, 1513],
 [datetime.date(2014, 12, 13), 214, 51, 2609, 1513],
 [datetime.date(2014, 12, 14), 214, 51, 2609, 1513],
 [datetime.date(2014, 12, 15), 214, 51, 2609, 1513],
 [datetime.date(2014, 12, 16), 214, 51, 2609, 1513],
 [datetime.date(2014, 12, 17), 214, 51, 2609, 1513],
 [datetime.date(2014, 12, 18), 214, 51, 2610, 1514],
 [datetime.date(2014, 12, 19), 214, 51, 2610, 1514],
 [datetime.date(2014, 12, 20), 215, 51, 2611, 1514],
 [datetime.date(2014, 12, 21), 215, 51, 2611, 1514],
 [datetime.date(2014, 12, 22), 215, 51, 2611, 1514],
 [datetime.date(2014, 12, 23), 215, 51, 2611, 1515],
 [datetime.date(2014, 12, 24), 215, 51, 2612, 1515],
 [datetime.date(2014, 12, 25), 215, 51, 2614, 1516],
 [datetime.date(2014, 12, 26), 215, 51, 2615, 1516],
 [datetime.date(2014, 12, 27), 215, 51, 2617, 1517],
 [datetime.date(2014, 12, 28), 215, 51, 2617, 1517],
 [datetime.date(2014, 12, 29), 215, 51, 2617, 1517],
 [datetime.date(2014, 12, 30), 215, 51, 2617, 1517],
 [datetime.date(2014, 12, 31), 215, 51, 2618, 1518],
 [datetime.date(2015, 1, 1), 215, 51, 2619, 1518],
 [datetime.date(2015, 1, 2), 215, 51, 2620, 1519],
 [datetime.date(2015, 1, 3), 215, 51, 2620, 1519],
 [datetime.date(2015, 1, 4), 215, 51, 2620, 1519],
 [datetime.date(2015, 1, 5), 215, 51, 2620, 1519],
 [datetime.date(2015, 1, 6), 215, 51, 2621, 1519],
 [datetime.date(2015, 1, 7), 215, 51, 2622, 1519],
 [datetime.date(2015, 1, 8), 215, 51, 2622, 1519],
 [datetime.date(2015, 1, 9), 215, 51, 2622, 1519],
 [datetime.date(2015, 1, 10), 215, 51, 2622, 1519],
 [datetime.date(2015, 1, 11), 215, 51, 2622, 1519],
 [datetime.date(2015, 1, 12), 215, 51, 2622, 1519],
 [datetime.date(2015, 1, 13), 215, 51, 2623, 1519],
 [datetime.date(2015, 1, 14), 215, 51, 2625, 1520],
 [datetime.date(2015, 1, 15), 215, 51, 2625, 1520],
 [datetime.date(2015, 1, 16), 215, 51, 2626, 1520],
 [datetime.date(2015, 1, 17), 215, 51, 2628, 1522],
 [datetime.date(2015, 1, 18), 215, 51, 2628, 1522],
 [datetime.date(2015, 1, 19), 215, 51, 2628, 1522],
 [datetime.date(2015, 1, 20), 215, 51, 2628, 1522],

In [12]:
c = ["日期", "殯葬", "餐廳", "花卉銷售", "花卉栽種"]
df = pd.DataFrame(np.array(c_with_uni_date), columns=c)
df

              日期   殯葬  餐廳  花卉銷售  花卉栽種
0     2014-01-01  198  48  2440  1426
1     2014-01-02  198  48  2440  1426
2     2014-01-03  198  48  2440  1427
3     2014-01-04  198  48  2442  1427
4     2014-01-05  198  48  2442  1427
5     2014-01-06  198  48  2442  1427
6     2014-01-07  198  48  2442  1427
7     2014-01-08  198  48  2442  1427
8     2014-01-09  198  48  2443  1427
9     2014-01-10  198  48  2443  1427
10    2014-01-11  198  48  2443  1427
11    2014-01-12  198  48  2443  1427
12    2014-01-13  198  48  2443  1427
13    2014-01-14  198  48  2443  1427
14    2014-01-15  198  48  2444  1429
15    2014-01-16  198  48  2446  1429
16    2014-01-17  198  48  2448  1429
17    2014-01-18  198  48  2448  1430
18    2014-01-19  198  48  2448  1430
19    2014-01-20  198  48  2448  1430
20    2014-01-21  198  48  2449  1430
21    2014-01-22  198  48  2449  1430
22    2014-01-23  198  48  2450  1431
23    2014-01-24  198  48  2451  1431
24    2014-01-25  198  48  2452  1431
25    2014-01-26  198  48  2452  1431
26    2014-01-27  198  48  2452  1431
27    2014-01-28  198  48  2452  1431
28    2014-01-29  198  48  2452  1431
29    2014-01-30  198  48  2453  1431
...          ...  ...  ..   ...   ...
1886  2019-03-02  277  69  3360  2018
1887  2019-03-03  277  69  3360  2018
1888  2019-03-04  277  69  3359  2017
1889  2019-03-05  277  69  3359  2017
1890  2019-03-06  277  69  3359  2017
1891  2019-03-07  277  69  3358  2017
1892  2019-03-08  277  69  3357  2017
1893  2019-03-09  277  69  3357  2017
1894  2019-03-10  277  69  3356  2016
1895  2019-03-11  277  69  3356  2016
1896  2019-03-12  277  69  3356  2016
1897  2019-03-13  277  69  3356  2016
1898  2019-03-14  277  69  3356  2016
1899  2019-03-15  277  69  3356  2016
1900  2019-03-16  277  69  3356  2016
1901  2019-03-17  277  69  3356  2016
1902  2019-03-18  275  69  3354  2016
1903  2019-03-19  275  69  3354  2016
1904  2019-03-20  275  69  3354  2016
1905  2019-03-21  275  69  3354  2016
1906  2019-03-22  275  69  3354  2016
1907  2019-03-23  275  69  3354  2016
1908  2019-03-24  275  69  3354  2016
1909  2019-03-25  275  69  3354  2016
1910  2019-03-26  275  69  3354  2016
1911  2019-03-27  275  69  3354  2016
1912  2019-03-28  275  69  3354  2016
1913  2019-03-29  275  69  3354  2016
1914  2019-03-30  275  69  3354  2016
1915  2019-03-31  275  69  3354  2016

[1916 rows x 5 columns]

In [13]:
# df.to_csv("uni_cout_bydate.csv", index=False, encoding="utf-8" )

In [15]:
c_without_uni_date=[]
for i in range(total_d):
    date = cdate[i]
    b_op = opdata[i]*1 # 該時間點已開張的條件
#     b_uni = (d_arr[:, 3]=="Y")*1
    result = []
    result.append(date)
    for c in range(8,11+1):
        b_c = (d_arr[:, c]==1)*1
        b = (b_op*b_c).astype(bool)
        result.append(len(d_arr[b, :]))
    c_without_uni_date.append(result)

In [16]:
c = ["日期", "殯葬", "餐廳", "花卉銷售", "花卉栽種"]
df = pd.DataFrame(np.array(c_without_uni_date), columns=c)
df

              日期   殯葬   餐廳   花卉銷售  花卉栽種
0     2014-01-01  748  161  13809  3854
1     2014-01-02  748  161  13811  3855
2     2014-01-03  748  161  13813  3858
3     2014-01-04  748  161  13816  3858
4     2014-01-05  748  161  13816  3858
5     2014-01-06  748  161  13816  3858
6     2014-01-07  748  161  13817  3858
7     2014-01-08  748  161  13819  3859
8     2014-01-09  748  161  13821  3859
9     2014-01-10  748  161  13824  3859
10    2014-01-11  748  161  13824  3859
11    2014-01-12  748  161  13824  3859
12    2014-01-13  748  161  13824  3859
13    2014-01-14  748  161  13825  3859
14    2014-01-15  748  161  13827  3861
15    2014-01-16  748  161  13830  3861
16    2014-01-17  748  161  13833  3862
17    2014-01-18  748  161  13833  3863
18    2014-01-19  748  161  13833  3863
19    2014-01-20  748  161  13833  3863
20    2014-01-21  748  161  13835  3864
21    2014-01-22  748  161  13836  3865
22    2014-01-23  748  161  13837  3868
23    2014-01-24  748  161  13839  3868
24    2014-01-25  748  161  13842  3868
25    2014-01-26  748  161  13842  3868
26    2014-01-27  748  161  13842  3868
27    2014-01-28  748  161  13843  3869
28    2014-01-29  748  161  13844  3871
29    2014-01-30  748  161  13845  3871
...          ...  ...  ...    ...   ...
1886  2019-03-02  872  202  16125  4728
1887  2019-03-03  872  202  16124  4728
1888  2019-03-04  872  202  16123  4727
1889  2019-03-05  872  202  16127  4727
1890  2019-03-06  872  202  16129  4729
1891  2019-03-07  872  203  16129  4730
1892  2019-03-08  872  203  16128  4731
1893  2019-03-09  872  203  16132  4731
1894  2019-03-10  872  203  16131  4730
1895  2019-03-11  871  203  16130  4730
1896  2019-03-12  870  203  16130  4730
1897  2019-03-13  870  203  16132  4732
1898  2019-03-14  871  203  16134  4732
1899  2019-03-15  871  203  16130  4727
1900  2019-03-16  871  203  16129  4727
1901  2019-03-17  871  203  16129  4727
1902  2019-03-18  869  203  16126  4727
1903  2019-03-19  869  203  16126  4727
1904  2019-03-20  869  203  16127  4730
1905  2019-03-21  869  203  16129  4729
1906  2019-03-22  869  203  16132  4729
1907  2019-03-23  869  203  16133  4729
1908  2019-03-24  869  203  16133  4729
1909  2019-03-25  868  202  16132  4727
1910  2019-03-26  868  202  16133  4727
1911  2019-03-27  868  202  16136  4729
1912  2019-03-28  868  202  16138  4728
1913  2019-03-29  868  202  16138  4727
1914  2019-03-30  868  202  16140  4727
1915  2019-03-31  868  202  16140  4727

[1916 rows x 5 columns]

In [17]:
df.to_csv("cout_bydate.csv", index=False, encoding="utf-8" )

In [18]:
sumfund_date=[]
for i in range(total_d):
    date = cdate[i]
    b_op = opdata[i]*1 # 該時間點已開張的條件
#     b_uni = (d_arr[:, 3]=="Y")*1
    result = []
    result.append(date)
    for c in range(8,11+1):
        b_c = (d_arr[:, c]==1)*1
        b = (b_op*b_c).astype(bool)
        result.append(sum(d_arr[b, 2]))
    sumfund_date.append(result)

In [19]:
c = ["日期", "殯葬", "餐廳", "花卉銷售", "花卉栽種"]
df = pd.DataFrame(np.array(sumfund_date), columns=c)
df

              日期          殯葬          餐廳          花卉銷售         花卉栽種
0     2014-01-01  2005579620  2540020360  117127596045  32017085920
1     2014-01-02  2005579620  2540020360  117128656045  32017145920
2     2014-01-03  2005579620  2540020360  117128766045  32024755920
3     2014-01-04  2005579620  2540020360  117129996045  32024755920
4     2014-01-05  2005579620  2540020360  117129996045  32024755920
5     2014-01-06  2005579620  2540020360  117129996045  32024755920
6     2014-01-07  2005579620  2540020360  117130296045  32024755920
7     2014-01-08  2005579620  2540020360  117130596045  32024758920
8     2014-01-09  2005579620  2540020360  117130796045  32024758920
9     2014-01-10  2005579620  2540020360  117131199045  32024758920
10    2014-01-11  2005579620  2540020360  117131199045  32024758920
11    2014-01-12  2005579620  2540020360  117131199045  32024758920
12    2014-01-13  2005579620  2540020360  117131199045  32024758920
13    2014-01-14  2005579620  2540020360  117131259045  32024758920
14    2014-01-15  2005579620  2540020360  117131489045  32027958920
15    2014-01-16  2005579620  2540020360  117132789045  32027958920
16    2014-01-17  2005579620  2540020360  117133119045  32028058920
17    2014-01-18  2005579620  2540020360  117133119045  32033058920
18    2014-01-19  2005579620  2540020360  117133119045  32033058920
19    2014-01-20  2005579620  2540020360  117133119045  32033058920
20    2014-01-21  2005579620  2540020360  117134119045  32033063920
21    2014-01-22  2005579620  2540020360  117134269045  32033263920
22    2014-01-23  2005579620  2540020360  117134769045  32035963920
23    2014-01-24  2005579620  2540020360  117135019045  32035963920
24    2014-01-25  2005579620  2540020360  117135469045  32035963920
25    2014-01-26  2005579620  2540020360  117135469045  32035963920
26    2014-01-27  2005579620  2540020360  117135469045  32035963920
27    2014-01-28  2005579620  2540020360  117135569045  32036063920
28    2014-01-29  2005579620  2540020360  117135572045  32038563920
29    2014-01-30  2005579620  2540020360  117138572045  32038563920
...          ...         ...         ...           ...          ...
1886  2019-03-02  1983905419  2587823360  120797585428  35168527272
1887  2019-03-03  1983905419  2587823360  120797385428  35168527272
1888  2019-03-04  1983905419  2587823360  120797185428  35168327272
1889  2019-03-05  1983905419  2587823360  120797540428  35167921272
1890  2019-03-06  1983905419  2587823360  120797940428  35170121272
1891  2019-03-07  1983905419  2588023360  120798000428  35170321272
1892  2019-03-08  1983905419  2588023360  120856000428  35170821272
1893  2019-03-09  1983905419  2588023360  120856310428  35170821272
1894  2019-03-10  1983905419  2588023360  120853310428  35167821272
1895  2019-03-11  1983900419  2588023360  120853280428  35167821272
1896  2019-03-12  1983897419  2588023360  120854080428  35167821272
1897  2019-03-13  1983897419  2588023360  120854330428  35168151272
1898  2019-03-14  1983997419  2588023360  120854285428  35171551272
1899  2019-03-15  1983997419  2588023360  120824285428  35143501272
1900  2019-03-16  1983997419  2588023360  120796885428  35143501272
1901  2019-03-17  1983997419  2588023360  120796885428  35143501272
1902  2019-03-18  1983557419  2588023360  120796217428  35143501272
1903  2019-03-19  1983557419  2588023360  120791220428  35143501272
1904  2019-03-20  1983557419  2588023360  120796220428  35155501272
1905  2019-03-21  1983557419  2588023360  120796488428  35153211272
1906  2019-03-22  1983557419  2588023360  120796898428  35153211272
1907  2019-03-23  1983557419  2588023360  120796998428  35153211272
1908  2019-03-24  1983557419  2588023360  120796998428  35153211272
1909  2019-03-25  1983357419  2585023360  120796798428  35144211272
1910  2019-03-26  1983357419  2585023360  120797248428  35144211272
1911  2019-03-27  1983357419  2585023360  120800666428  35147311272
1912  2019-03-28  1983357419  2585023360  120800834428  35147261272
1913  2019-03-29  1983357419  2585023360  120800834428  35137261272
1914  2019-03-30  1983357419  2585023360  120801574428  35137261272
1915  2019-03-31  1983357419  2585023360  120801574428  35137261272

[1916 rows x 5 columns]

In [20]:
df.to_csv("sumfund_date.csv", index=False, encoding="utf-8" )